behaviors:
  tank-optimized-01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      learning_rate: 0.0004
      beta: 1.0e-3
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.2
    max_steps: 500000
    time_horizon: 256
    summary_freq: 5000
#env_settings:
#  env_path: env-builds/TutorialRollerBallOptimizedEnv-build-v0.1.0/TutorialRollerBallOptimizedEnv.exe # Windows
#  num_envs: 32
#  seed: 20241007 # Environment-level seed
engine_settings:
  no_graphics: false
checkpoint_settings:
  run_id: tank-2024-11-10
  force: true
